name: Android E2E Test

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest-16
    timeout-minutes: 30
    steps:
      - name: Android E2E Test
        run: echo "Executing Android E2E Test"