name: Android E2E Test

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Appium CLI
        run: npm install -g appium

      - name: Install uiautomator2 driver
        run: appium driver install uiautomator2

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install Android SDK (Command Line Tools)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          force-avd-creation: false
          disable-animations: true
          script: ./gradlew connectedCheck

      - name: Wait for emulator
        run: adb wait-for-device

      - name: Set ANDROID_HOME environment variable
        run: echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV

      - name: Check Appium
        run: npx appium-doctor --android

      - name: Start Appium server in background
        id: start_appium
        run: |
          nohup npx appium --port 4723 > appium.log 2>&1 &
          echo "appium_pid=$!" >> $GITHUB_OUTPUT

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run unit tests
        run: ./gradlew :app:testDebugUnitTest

      - name: Show test failure summary
        if: failure()
        run: |
          echo "==================================== Failed Tests Summary ===================================="
          cat appium.log


      - name: Kill Appium process
        run: |
          echo "Killing Appium process with PID ${{ steps.start_appium.outputs.appium_pid }}"
          kill ${{ steps.start_appium.outputs.appium_pid }}

#      - name: Upload test-result.mp4
#        uses: actions/upload-artifact@v4
#        with:
#          name: test-video
#          path: app/test-result.mp4