name: Android E2E Test

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Appium CLI
        run: npm install -g appium

      - name: Install uiautomator2 driver
        run: appium driver install uiautomator2

      - name: Set ANDROID_HOME environment variable
        run: echo "ANDROID_HOME=$HOME/Library/Android/sdk" >> $GITHUB_ENV

      - name: Install Android SDK (Command Line Tools)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          force-avd-creation: false
          disable-animations: true
          script: echo "Android SDK setup complete"

      - name: Check Appium
        run: npx appium-doctor --android

      - name: Start Appium server in background
        id: start_appium
        run: |
          nohup npx appium > appium.log 2>&1 &
          echo "appium_pid=$!" >> $GITHUB_OUTPUT

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run unit tests
        run: ./gradlew :app:testDebugUnitTest

      - name: Kill Appium process
        run: |
          echo "Killing Appium process with PID ${{ steps.start_appium.outputs.appium_pid }}"
          kill ${{ steps.start_appium.outputs.appium_pid }}

      - name: Upload test-result.mp4
        uses: actions/upload-artifact@v4
        with:
          name: test-video
          path: app/test-result.mp4